// Code generated by mockery v0.0.0-dev. DO NOT EDIT.

package mocks

import (
	types "github.com/robstave/gorag/internal/domain/types"
	mock "github.com/stretchr/testify/mock"
)

// Domain is an autogenerated mock type for the Domain type
type Domain struct {
	mock.Mock
}

// Createdocument provides a mock function with given fields: document
func (_m *Domain) Createdocument(document types.Document) (*types.Document, error) {
	ret := _m.Called(document)

	var r0 *types.Document
	if rf, ok := ret.Get(0).(func(types.Document) *types.Document); ok {
		r0 = rf(document)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*types.Document)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(types.Document) error); ok {
		r1 = rf(document)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Deletedocument provides a mock function with given fields: documentID
func (_m *Domain) Deletedocument(documentID string) error {
	ret := _m.Called(documentID)

	var r0 error
	if rf, ok := ret.Get(0).(func(string) error); ok {
		r0 = rf(documentID)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// GetAlldocuments provides a mock function with given fields:
func (_m *Domain) GetAlldocuments() ([]types.Document, error) {
	ret := _m.Called()

	var r0 []types.Document
	if rf, ok := ret.Get(0).(func() []types.Document); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]types.Document)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func() error); ok {
		r1 = rf()
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetdocumentByID provides a mock function with given fields: documentID
func (_m *Domain) GetdocumentByID(documentID string) (*types.Document, error) {
	ret := _m.Called(documentID)

	var r0 *types.Document
	if rf, ok := ret.Get(0).(func(string) *types.Document); ok {
		r0 = rf(documentID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*types.Document)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(string) error); ok {
		r1 = rf(documentID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Seeddocument provides a mock function with given fields:
func (_m *Domain) Seeddocument() error {
	ret := _m.Called()

	var r0 error
	if rf, ok := ret.Get(0).(func() error); ok {
		r0 = rf()
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// Updatedocument provides a mock function with given fields: document
func (_m *Domain) Updatedocument(document types.Document) (*types.Document, error) {
	ret := _m.Called(document)

	var r0 *types.Document
	if rf, ok := ret.Get(0).(func(types.Document) *types.Document); ok {
		r0 = rf(document)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*types.Document)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(types.Document) error); ok {
		r1 = rf(document)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

type mockConstructorTestingTNewDomain interface {
	mock.TestingT
	Cleanup(func())
}

// NewDomain creates a new instance of Domain. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
func NewDomain(t mockConstructorTestingTNewDomain) *Domain {
	mock := &Domain{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
