// Code generated by mockery v0.0.0-dev. DO NOT EDIT.

package mocks

import (
	mock "github.com/stretchr/testify/mock"

	types "github.com/robstave/gorag/internal/domain/types"
)

// Repository is an autogenerated mock type for the Repository type
type Repository struct {
	mock.Mock
}

// Createdocument provides a mock function with given fields: document
func (_m *Repository) Createdocument(document types.Document) error {
	ret := _m.Called(document)

	var r0 error
	if rf, ok := ret.Get(0).(func(types.Document) error); ok {
		r0 = rf(document)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// Deletedocument provides a mock function with given fields: id
func (_m *Repository) Deletedocument(id string) error {
	ret := _m.Called(id)

	var r0 error
	if rf, ok := ret.Get(0).(func(string) error); ok {
		r0 = rf(id)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// GetAlldocuments provides a mock function with given fields:
func (_m *Repository) GetAlldocuments() ([]types.Document, error) {
	ret := _m.Called()

	var r0 []types.Document
	if rf, ok := ret.Get(0).(func() []types.Document); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]types.Document)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func() error); ok {
		r1 = rf()
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetdocumentById provides a mock function with given fields: id
func (_m *Repository) GetdocumentById(id string) (*types.Document, error) {
	ret := _m.Called(id)

	var r0 *types.Document
	if rf, ok := ret.Get(0).(func(string) *types.Document); ok {
		r0 = rf(id)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*types.Document)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(string) error); ok {
		r1 = rf(id)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Updatedocument provides a mock function with given fields: document
func (_m *Repository) Updatedocument(document types.Document) error {
	ret := _m.Called(document)

	var r0 error
	if rf, ok := ret.Get(0).(func(types.Document) error); ok {
		r0 = rf(document)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

type mockConstructorTestingTNewRepository interface {
	mock.TestingT
	Cleanup(func())
}

// NewRepository creates a new instance of Repository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
func NewRepository(t mockConstructorTestingTNewRepository) *Repository {
	mock := &Repository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
