// Code generated by mockery v0.0.0-dev. DO NOT EDIT.

package mocks

import (
	mock "github.com/stretchr/testify/mock"

	types "github.com/robstave/gorag/internal/domain/types"
)

// Repository is an autogenerated mock type for the Repository type
type Repository struct {
	mock.Mock
}

// CreateWidget provides a mock function with given fields: widget
func (_m *Repository) CreateWidget(widget types.Widget) error {
	ret := _m.Called(widget)

	var r0 error
	if rf, ok := ret.Get(0).(func(types.Widget) error); ok {
		r0 = rf(widget)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// DeleteWidget provides a mock function with given fields: id
func (_m *Repository) DeleteWidget(id string) error {
	ret := _m.Called(id)

	var r0 error
	if rf, ok := ret.Get(0).(func(string) error); ok {
		r0 = rf(id)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// GetAllWidgets provides a mock function with given fields:
func (_m *Repository) GetAllWidgets() ([]types.Widget, error) {
	ret := _m.Called()

	var r0 []types.Widget
	if rf, ok := ret.Get(0).(func() []types.Widget); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]types.Widget)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func() error); ok {
		r1 = rf()
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetWidgetById provides a mock function with given fields: id
func (_m *Repository) GetWidgetById(id string) (*types.Widget, error) {
	ret := _m.Called(id)

	var r0 *types.Widget
	if rf, ok := ret.Get(0).(func(string) *types.Widget); ok {
		r0 = rf(id)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*types.Widget)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(string) error); ok {
		r1 = rf(id)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// UpdateWidget provides a mock function with given fields: widget
func (_m *Repository) UpdateWidget(widget types.Widget) error {
	ret := _m.Called(widget)

	var r0 error
	if rf, ok := ret.Get(0).(func(types.Widget) error); ok {
		r0 = rf(widget)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

type mockConstructorTestingTNewRepository interface {
	mock.TestingT
	Cleanup(func())
}

// NewRepository creates a new instance of Repository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
func NewRepository(t mockConstructorTestingTNewRepository) *Repository {
	mock := &Repository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
